### ISSUE TITLE
Description Regex

### ISSUE THREAD

**Issue by mdhelaluddin-ctg-bd** [FabianBeiner/PHP-IMDB-Grabber#100]
Hi,
I see this class not getting the description of the movie.
Can you add another function called getDescription() which will return description of the movie?
Thanks

**Comment by FabianBeiner** [comment]
Can you give an example for what you're looking for? Maybe it's already covered with `getTagline()` or `getPlot()`?

**Comment by mdhelaluddin-ctg-bd** [comment]
For example if you visit this url
https://www.imdb.com/title/tt4456850/
Descrition of this movie is
"Two teen rival babysitters, Jenny and Lola, team up to hunt down one of their kids who accidentally runs away into the big city without any supervision."
But getPlot() and getTagline() returning "N/A"

**Comment by FabianBeiner** [comment]
Added in v6.1.0. 👍
