### ISSUE TITLE
Cast Image

### ISSUE THREAD

**Issue by shamdin** [FabianBeiner/PHP-IMDB-Grabber#101]
Hi and thanks great to have a developer that talented. 
I have added     $IMDB->getPoster($sSize = 'small', $bDownload = true) . i get image path again not a poster. 

Update: image path was wrong solved it 👍 

final request if it possible to add cast image it would be totally 💯% awesome 

thanks for the help

**Comment by FabianBeiner** [comment]
Hi @shamdin!

What you mentioned is exactly the behavior as it should be. :) As you said, `$IMDB->getPoster('small', true)` downloads the small poster, saves it into `posters` folder, and returns the path. You can use this one then as `src` on any `<img>` tag. Same for the method where you don't download the image.

And about the cast image: What's that? ;) Can you show me some examples?

Cheers!

**Comment by shamdin** [comment]
Hi @FabianBeiner  

Thanks for answering, 
here is a url https://www.imdb.com/title/tt4154756/?ref_=inth_ov_tt
under Cast overview is the cast and there images.

I have another problem but it need a developer like you maybe solve it, I sent you a email I hoped i not I did wrong to ask for advice!

Again thanks

**Comment by FabianBeiner** [comment]
I'll look into this one day, but don't count on it anytime soon. Sorry!

**Comment by bla0r** [comment]
At first i found a way to get small,mid and high cast images. 
So if i have the time to do that i will commit it.

**Comment by shamdin** [comment]
Hi @bla0r and @FabianBeiner

Wow, to wake up to this information made me so happy! 
I hope to see this future very soon.

**Comment by bla0r** [comment]
@shamdin i pulled a request to get cast images, see #102

**Comment by bla0r** [comment]
Poster is only one Image. You have to split  the array, because there are multiple images.

**Comment by shamdin** [comment]
I get one cast image so if I want to show more than one I have to split the array? due to im a newbie is there a example I would appreciate it. thanks

**Comment by FabianBeiner** [comment]
Thanks, @bla0r. @shamdin, check the example file. I've added some stuff there for you.
