### ISSUE TITLE
Image size issue

### ISSUE THREAD

**Issue by shamdin** [FabianBeiner/PHP-IMDB-Grabber#103]
Hi everyone!
Great job the team behind the imdb grabber you all make this happen.
Im grateful again Thanks
I use this code to get big images and for the most part around 70% of the time I get big picture but the 30% I get small images and it is set to big as you can see here.

`   $img_src = $IMDB->getCastImage($iLimit = 6, $bMore = false, $sSize = 'big', $bDownload = true);`
any clue why it gets small images I have sett the image to 200px x 200px and the small images is awful.

Here is a example and again it set to big
https://snag.gy/91kjr8.jpg

Again thank I hope this information will help you guys to make this a great script!

**Comment by MARGELANI** [comment]
try to get "mid" size.

**Comment by bla0r** [comment]
You're right @shamdin. In some cases the 'big' image isn't available, but a 'mid' one and vice versa. I'll code a image check fot that.

**Comment by bla0r** [comment]
@shamdin pulled a request #104 and it's coming up with a new function to get all release dates for each country
