### ISSUE TITLE
Missing poster

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#107]
From today, i get empty posters.

**Comment by bla0r** [comment]
@maknol fixed see #108

**Comment by maknol** [comment]
Tested with https://www.imdb.com/title/tt0063634 - not working for me

**Comment by FabianBeiner** [comment]
I can't confirm this, not even with the movie @maknol provided:

![Proof](https://user-images.githubusercontent.com/86269/40917444-94495aae-6803-11e8-8bfb-3ae280f5ddef.png)

Closing this for now.
