### ISSUE TITLE
Total Gross worldwide

### ISSUE THREAD

**Issue by kumarrahulkush** [FabianBeiner/PHP-IMDB-Grabber#109]
Please add a function to get Total Gross worldwide. it has no option for this. You just have  to add a regular expression which find total gross worldwide collection it will not take too much. I tried to do this but didn't success. After adding this function your code will be absolute.

**Comment by bla0r** [comment]
the cumulative worldwide gross is not available for all movies. But I can add it.

**Comment by bla0r** [comment]
request has been pulled out. #111
