### ISSUE TITLE
Regex since update

### ISSUE THREAD

**Issue by conyum** [FabianBeiner/PHP-IMDB-Grabber#110]
Imdb has yet again changed their code and the regex for poster, plot and rating doesnt work anymore.
Anyone figured out a new regex for this ?

**Comment by bla0r** [comment]
all of them are working for me.

**Comment by conyum** [comment]
https://i.imgur.com/gCBWdwV.jpg
That is all that returns when running a imdb id for me.
Tried the latest imdb.class.php too...

**Comment by bla0r** [comment]
well, if you check the reference page, there are no information available.

**Comment by conyum** [comment]
It might be so that the elliot isnt correct.
According to the debug it uses this id https://www.imdb.com/title/tt6505968/reference
But returns Elliot

**Comment by conyum** [comment]
Fixed it.
It was something in the cache-folder that went bananas. 
Cleared out all cache and it now returns the correct imdb.
Thanks anyway.
