### ISSUE TITLE
IMDB's display title not pulling

### ISSUE THREAD

**Issue by BrianSpan** [FabianBeiner/PHP-IMDB-Grabber#113]
www.imdb.com/title/tt6878882   displays on IMDB's page as "Operation Red Sea". No matter how I set the value to getTitle(), I don't get that title.

**Comment by FabianBeiner** [comment]
No, the title of that movie is  `Hong hai xing dong`: 

![screenshot-www imdb com-2018 08 26-19-20-12](https://user-images.githubusercontent.com/86269/44630917-1261f200-a965-11e8-9765-38a7645ee5b2.png)

`Operation Red Sea` should be listed in the AKAs.

**Comment by BrianSpan** [comment]
I wonder why my IMDB is showing a different title? 
![tt6878882](https://user-images.githubusercontent.com/15399440/44688769-1b58cf00-aa0a-11e8-94ea-72cd5e3c44ae.png)

**Comment by FabianBeiner** [comment]
Because you're getting the localized title. Try using `getTitle(true)`, which tries to return the original name of the movie. :)
