### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by theshahzaibc** [FabianBeiner/PHP-IMDB-Grabber#115]
Hello, I used your class but no more it's working

**Comment by FabianBeiner** [comment]
Please read https://github.com/FabianBeiner/PHP-IMDB-Grabber#bugs and post the details here.

**Comment by nasir6767** [comment]
like this after BUG is true

Running: fetchUrl("http://us.imdb.com/Title?0144117")
Using cache: 9924c9c40c2d6b5468e4812eb2e73ea1990a0d03.cache
n/A got rated n/A.

Running: fetchUrl("New York, I Love You")
Running cURL: https://www.imdb.com/find?q=New+York,+I+Love+You&s=tt
cURL returned wrong HTTP code “0”, aborting.
n/A
Url: https://www.imdb.com/find?q=New+York,+I+Love+You&s=tt

**Comment by FabianBeiner** [comment]
**FYI: I just ran the latest version of the script again, and everything is working fine here. There is nothing to fix nor to update. Sorry, nothing I can do.**

> Running: fetchUrl("http://us.imdb.com/Title?0144117")
> Using cache: 9924c9c40c2d6b5468e4812eb2e73ea1990a0d03.cache
> n/A got rated n/A.

This might be an old cache. I'd recommend cleaning `/cache/ `.

> Running: fetchUrl("New York, I Love You")
> Running cURL: https://www.imdb.com/find?q=New+York,+I+Love+You&s=tt
> cURL returned wrong HTTP code “0”, aborting.

HTTP 0 is probably a local problem because it never reached imdb.com.

**Comment by nasir6767** [comment]
I tried using another title but it didn't work, and I used the latest version

**Comment by FabianBeiner** [comment]
As said: For now I have to believe it's some local issue on your side. There is nothing I can fix. :(
