### ISSUE TITLE
& in title leads to wrong search

### ISSUE THREAD

**Issue by chrismelis** [FabianBeiner/PHP-IMDB-Grabber#118]
If a title includes the symbol & then the results are wrong.
For example:
Pain & Gain (2013) - the search gets the title Vile
21 & Over (2013) - the search gets the title 21 (which is a different movie)

**Comment by FabianBeiner** [comment]
Nope, can't reproduce this. Give me exactly what I've been searching for, and I tested your suggestions.

**Comment by FabianBeiner** [comment]
Sorry, there is still nothing I can do. It is working, and I don't have an error to fix. :(

**Comment by chrismelis** [comment]
Do you get the correct results???
I tried several movies with & in the title and none of them is working properly. This is a bug for sure

**Comment by FabianBeiner** [comment]
As I mentioned before, I do get the correct results. But here, have a screenshot of it:

![2018 11 03-20-01-32](https://user-images.githubusercontent.com/86269/47956347-5b58a700-dfa3-11e8-9dfb-03c95c1233d9.png)

**Comment by chrismelis** [comment]
Thanks Fabian. 
Probably something else is the problem. I will continue my search.
Cheers

**Comment by FabianBeiner** [comment]
Make sure you're using the latest version, and maybe enable debug to find out an actual error. Then let me know! Good luck :)

**Comment by chrismelis** [comment]
Dear Fabian,
After downloading the latest version the problem with & is solved but there is another strange behavior.
The titles are in another language maybe Spanish. See below images

![2018-11-03_21-09-45](https://user-images.githubusercontent.com/10847273/47957577-81387880-dfb0-11e8-94f0-160eeead2256.jpg)
![2018-11-03_21-11-22](https://user-images.githubusercontent.com/10847273/47957578-81387880-dfb0-11e8-844b-73e5d1d8f28d.jpg)
![2018-11-03_21-17-19](https://user-images.githubusercontent.com/10847273/47957579-81387880-dfb0-11e8-9fdb-83b94b13133b.jpg)

**Comment by FabianBeiner** [comment]
Please read about the behavior of getTitle().

**Comment by chrismelis** [comment]
I missed that option.
Now everything is perfect.
Nice job my friend.
