### ISSUE TITLE
Accept-Language not really working

### ISSUE THREAD

**Issue by MacMillan13** [FabianBeiner/PHP-IMDB-Grabber#124]
`const IMDB_LANG = 'en-US,en;q=0.9';`
When I send a request I get response part on english, part on ukranian(here is my server).
Tried to set true in function `$imdbList->getTitles(true);`, but don't help.
Maybe somebody know how to fix it. Need pure english. Will be very grateful for the help. Thanks.

**Comment by FabianBeiner** [comment]
If this won't help, you'll most likely need a proxy or a web host in the US.

**Comment by MacMillan13** [comment]
Thanks.
