### ISSUE TITLE
Company and Aka Result Wrong

### ISSUE THREAD

**Issue by webmaster-sites** [FabianBeiner/PHP-IMDB-Grabber#127]
the getCompany method has problem
for example for :
https://www.imdb.com/title/tt0468569/?ref_=nv_sr_srsg_0
the getCompany  outputs "Warner Bros." as single item,but the original imdb is "Warner Bros., Legendary Entertainment, Syncopy"
-------------------------------------------------
and getAka in world wide item we need but it does not returns!

**Comment by bla0r** [comment]
you're right, it's a regex problem, trying to solve it

**Comment by bla0r** [comment]
@FabianBeiner  fixed, can be closed
