### ISSUE TITLE
year problem for series

### ISSUE THREAD

**Issue by webmaster-sites** [FabianBeiner/PHP-IMDB-Grabber#128]
for example
https://www.imdb.com/title/tt0412253/

the year should be an array of  2019   2007   2006   2005   2004   
but it returns only 2004

**Comment by bla0r** [comment]
we parse the reference page not that one you posted. but i'll add it 👍

**Comment by FabianBeiner** [comment]
> we parse the reference page not that one you posted. but i'll add it 👍

Mate, please take note that IMDb is going to use their new layout anytime soon globally, I guess. So, every new implementation will most likely only be valid for a few weeks, maybe a few months.
