### ISSUE TITLE
description problem in series

### ISSUE THREAD

**Issue by webmaster-sites** [FabianBeiner/PHP-IMDB-Grabber#129]
for example
https://www.imdb.com/title/tt0412253/

it returns :
    [Description] => Seasons: 12 11 10 ... See all » Years: 2019 2018 2017 ... See all »

that is wrong!
but for movie types it works correctly!!!

**Comment by bla0r** [comment]
fixed #136

**Comment by FabianBeiner** [comment]
Thanks! <3
