### ISSUE TITLE
metacritic score

### ISSUE THREAD

**Issue by Jergis** [FabianBeiner/PHP-IMDB-Grabber#130]
Hi

Please add a function to get metacritic score from page

thanks

**Comment by Cyclonecode** [comment]
This data is not included in the reference page: https://www.imdb.com/title/tt0078748/reference
instead one would need to fetch this from a page like: https://www.imdb.com/title/tt0078748/criticreviews?ref_=tt_ql_op_6

**Comment by bla0r** [comment]
@Jergis i will implement this

**Comment by bla0r** [comment]
@Jergis i add a pull request on this. You can check it out #135

**Comment by FabianBeiner** [comment]
Thanks for your work, @bla0r :)
