### ISSUE TITLE
grabbing cast and directors detail by imdb id = nm0001609

### ISSUE THREAD

**Issue by masoodsajedi** [FabianBeiner/PHP-IMDB-Grabber#131]
how can i get cast and .. detail by id like nm0001609

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by maknol** [comment]
You can do it like:
`public function getMusicAsNameAndID($sTarget = '')
    {
        if (true === $this->isReady) {
            $sMatch  = IMDBHelper::matchRegex($this->sSource, self::IMDB_MUSIC, 1);
            $aMatch  = IMDBHelper::matchRegex($sMatch, self::IMDB_NAME);
            $aReturn = [];
            if (count($aMatch[2])) {
                foreach ($aMatch[2] as $i => $sName) {
                    $aReturn[] = IMDBHelper::cleanString($aMatch[1][$i]) . '@' .IMDBHelper::cleanString($sName);
                }

                return IMDBHelper::arrayOutput($this->bArrayOutput, $this->sSeparator, self::$sNotFound, $aReturn);
            }
        }

        return IMDBHelper::arrayOutput($this->bArrayOutput, $this->sSeparator, self::$sNotFound);
    }`

After that calling it with: $oIMDB->getMusicAsNameAndID();
I put separator here '@', but it can be anything.
Result: nm00000001@Some Name

**Comment by FabianBeiner** [comment]
This has been lying around here for almost four years. Since the tread opener never came back with any feedback, I'll close it. 🙈
