### ISSUE TITLE
The functions getAkas and getReleaseDates does not return any data

### ISSUE THREAD

**Issue by santajrr** [FabianBeiner/PHP-IMDB-Grabber#132]
When calling the functions getAkas or getReleaseDates for e.g. "The Shamer's Daughter" (tt3022458), no data is returned even though there are several akas and release dates for the before mentioned title.

**Comment by Cyclonecode** [comment]
This works just fine for me, I get the following data returned:

`getAkas()` => "Dcera čarodějky (Czech Republic) | Skämmerskans dotter (Sweden) | The Shamer's Daughter (World-wide, English title) | The Shamer (France) | Die Hüterin der Wahrheit - Dinas Bestimmung (Germany)"
`getReleaseDates()` => "26 Mar 2015 (Denmark)"

**Comment by bla0r** [comment]
@santajrr i fixed it. You can check it at Pull Requests!

**Comment by FabianBeiner** [comment]
Thanks for the fix, @bla0r!
