### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ExYuSubs** [FabianBeiner/PHP-IMDB-Grabber#133]
Someone who have update of this hack, thanks

**Comment by FabianBeiner** [comment]
What exactly do you mean?

**Comment by ExYuSubs** [comment]
Hi, I can't make it to work.
It don't scrape data from iMDB

**Comment by FabianBeiner** [comment]
@ExYuSubs: Please use the latest version and give it a try again. If the problem still occurs, enable debug and open another issue. Thanks!
