### ISSUE TITLE
problem with original vs used title for foreign movies

### ISSUE THREAD

**Issue by lord-aceldama** [FabianBeiner/PHP-IMDB-Grabber#142]
defaults to original title (no akas)

example: https://www.imdb.com/title/tt8963328/

Hi Score Girl 
Hai Sukoa Garu (original title)

**Comment by lord-aceldama** [comment]
just wanted to add, you do awesome work. thanks for the effort.

**Comment by bla0r** [comment]
if you want the original title use getTitle($bForceLocal = true)

**Comment by lord-aceldama** [comment]
brilliant! thanks :D
