### ISSUE TITLE
inconsistent array delimiter

### ISSUE THREAD

**Issue by lord-aceldama** [FabianBeiner/PHP-IMDB-Grabber#147]
non-standard array delimiters in `Aka` and `Cetification` sections of getAll(). the standard ` / ` is expected (see `IMDB::$sSeparator`), but got ` | ` instead.

url: `https://www.imdb.com/title/tt8963328/`
sample values (var_dump):
`string(178) "ハイスコアガール (Japan, Japanese title) | High Score Girl (United States) | Hi Score Girl (World-wide, English title) | High Score Girl (France) | Hi Score Girl (Norway)"`

`string(254) "Argentina:13 | Australia:M (Season 1) | France:13 (self-applied) | Germany:12 | Italy:T | Netherlands:6 | Norway:12 (Netflix self-rating) | Singapore:PG13 | Spain:13 | United Kingdom:12 | United States:TV-PG | United States:TV-14 (Season 2) | Vietnam:C13"`

**Comment by bla0r** [comment]
you're right, because it will return a string and not an array. So in that case we have to seperate each ' | ' and parse them to an array.

**Comment by bla0r** [comment]
fixed, can be closed
