### ISSUE TITLE
Imdb Grabber stopped working last night

### ISSUE THREAD

**Issue by Artbabe** [FabianBeiner/PHP-IMDB-Grabber#150]
Last night imdb changed their layout/code
and functions are not working anymore
getPlot [summary_text]
and
getPoster
and few others tested
but most of us need these 2 items

**Comment by bla0r** [comment]
i can't confirm it... can you post further details

**Comment by Artbabe** [comment]
Please check the sites !!
it was armagedon
imdb changed their layout and code last night
I changed <DIV... s and updated them and I got it working (I only need getPlot/summary
and poster/big
BUT
Now , after recent change in imdb , we need to add a new feature to fabian's code
because getURL now is big problem
for example
when there are 2 same name/different year for movie , it always gets updater one
like for example
Adam 1950
Adam 2020
it always gets Adam 2020

I did this by adding SEARCH option to TVDB 's code [my coder did it NOT me]
now fabian's script needs SEARCH option to get correct result for
getURL

good luck BTW

**Comment by bla0r** [comment]
we don't crawl the mainpage! The Grabber is parsing the reference page. For example: /tt0..../reference
The search page hasn't been changed either.

**Comment by Artbabe** [comment]
I fixed regex even I added several alternate for getPLOT
[it has reason bcuz there are 4 types of regex for getplot/summary

Plot is not as good as summary

[BTW , my coder did it , NOT me ]

but
the biggest problem which started 2 days ago when I reported the change in imdb is:
its getting many wrong result for
getURL

this is big problem now
my another coder suggested that based-on huge wrong result , he wants to add a new feature to Fabian's code
which separates
title
from
year
and searches kinda 2 times !!

please ,look at this:

we sent
Mission Impossible 1996
https://www.imdb.com/title/tt0117060/

it gets:
https://www.imdb.com/title/tt9603212/
Mission: Impossible 7 (2022)

-------------

The Well Diggers Daughter 1940

 gets:
https://www.imdb.com/title/tt1473063/
The Well Digger's Daughter (2011)

correct is:
https://www.imdb.com/title/tt0033603/

===========
we sent this title to imdb's script:
Run 2020
https://www.imdb.com/title/tt8633478/
doesn't get anything

===========

Boogie 2021
it must get: https://www.imdb.com/title/tt10896398/
but it gets:  https://www.imdb.com/title/tt2960304/

=============


Journey Into Fear 1975
https://www.imdb.com/title/tt0073213/

imdb script gets:
Journey Into Fear 1943
https://www.imdb.com/title/tt0034922/



and sooooo many today's errors
the fact is Fabian 's code for years was our bible
but imdb changed their stuff
and unfortunately , this code is not reliable in getURL 's matter


do you have any tip I send to my coder?

**Comment by bla0r** [comment]
You're right. I will take a look on it. 
would be cool if you can share your plot regex.

**Comment by Artbabe** [comment]
please let him fix everything
I will send u the final code

please
look at this:
https://i.imgur.com/BCsGDki.jpg


this is so weird
few months ago tvdb changed their layout
and man , this is strange that , we started getting exactly same error

now imdb did change and getURL exactly is giving that error
the thing this coder did was:

he created a logic which was prioritizing the titles
and was picking closest title
which fixed the tvdb 100% [unbelievable indeed]

I will return back to you soon

please check these which happened in last minutes:


The Woman 2011
https://www.imdb.com/title/tt1714208/

it gets:
https://www.imdb.com/title/tt5472688/


===============================


The Gate 1987
https://www.imdb.com/title/tt0093075/

but gets
https://www.imdb.com/title/tt8965356/








it totally cant recognize items like:
https://www.imdb.com/title/tt6111130/


and gives: https://www.imdb.com/title/tt7761960/


it can't get:
Smile 1975
https://www.imdb.com/title/tt0073722/

**Comment by Artbabe** [comment]
this is really weird
since the day I reported here [actually seconds after imdb changed their code ,I reported here ]
getURL affected to the point that it cant even get 


Beginning (2020)
https://www.imdb.com/title/tt12444572/


also

The Beast Must Die 1974
it gives: https://www.imdb.com/title/tt9062784/

but its: https://www.imdb.com/title/tt0071200/

===================


From Beyond 1986
https://www.imdb.com/title/tt0091083/


but it gets
https://www.imdb.com/title/tt13085290/



====================




Evil Dead II 1987
https://www.imdb.com/title/tt0092991/

gets: https://www.imdb.com/title/tt6538700/

**Comment by Artbabe** [comment]
@Fabian:
bla0r is you ?!
don't you remember me?!

**Comment by bla0r** [comment]
i found a solution, will commit it later... have to test it

**Comment by Artbabe** [comment]
man
this has become a real problem for me
the problem comes from their SEARCH function
which is giving very wrong result for many cases
let me start working on your new solution

**Comment by Artbabe** [comment]
Dear moses
who are you?
you are fabian?
wow
what the extra terrestrially masterpiece of code you just did?!
does anyone know what did this coder just do?
seriously

wow
I sincerely admire your iq and skills
are you Fabian?

**Comment by FabianBeiner** [comment]
(No, @bla0r is not me. Sadly, I don't actually know who he is - but I promised him some beer 🍻 already because he's taking such good care of this project.)

**Comment by Artbabe** [comment]
@Fabian:
man he is in your level ,
believe me he did something unbelievable

I am sending the rest of the cases which require some changes
and let us make your script as Bible for imdb

here is 2 new cases

https://www.imdb.com/title/tt2142987/

and
A Dog's Courage (2018)
https://www.imdb.com/title/tt7852002/

**Comment by Artbabe** [comment]
oh btw
as soon as i finish my own changes
which are technically 2 people's changes
i will share the final script with you
which will be different with you
but to be honest
this code is good
and its almost impossible to write better than yours

**Comment by Artbabe** [comment]
I see one thing is clear
'character is a problem

this also just happened
Liberty's Secret (2016)
https://www.imdb.com/title/tt4396662/

legal title is:
Libertys.Secret.2016
which sites can use

**Comment by bla0r** [comment]
@Artbabe both of them are working for me. I can't confirm the char ' problem. Its a Wordpress problem. You should escape it. For example \'

**Comment by Artbabe** [comment]
using character in any platform [wordpress...] is illegal and causes problem
do you see even 1 character in RARBG's whole website?

please send
Loves Last Resort 2017
to your script
and all the othhers
it's giving empty response
or
Libertys Secret 2016
and others too
Your script is being used in such platforms

still
if you can't solve this problem
I fully understand
I am one of the people who use imdb grabber/scrapper and I am sending my concern


I must solve this problem , by you or by another Good person like yourself

**Comment by FabianBeiner** [comment]
@Artbabe: If you got a coder (and maybe even pay him), and you rely on this script so much - why not ask him to fix some more stuff and open a pull request here? :) @bla0r and I are doing this for fun, but that also means this has not the highest priority for both of us.

**Comment by bla0r** [comment]
If you checked the developer Page of wordpress you can escape these chars with: esc_attr( string $text )

**Comment by Artbabe** [comment]
oh i see
let me show this my coder

**Comment by Artbabe** [comment]
huge breakthrought

this part of the code is the problem
https://www.imdb.com/search/title/?title=

https://www.imdb.com/search/title/?title=Cant+Take+It+Back

**Comment by bla0r** [comment]
At first i thought of a better search routine:

```
- save each result ( title, year, id ) in a vector 
- comparing the search words with the result ones
- fetch that one with the highest agreement
```

But: you only get title results depends on your location and NOT the original ones - you can't compare them.

**Comment by Artbabe** [comment]
another huge break thro
I just found something which can reduce rate of error significantly
my coders are not around
so
can you tell me how I send Year of release in ()

go to imd
search for
Psychos 2017

see how ridiculous is result?

now
search
Psychos (2017)

see?

please tell me where i need to apply this change in your code?

**Comment by bla0r** [comment]
You can do it yourself.

`$IMDB = new IMDB('Psychos 2017', null, 'movie'); `

If you get no results use the other switches.

**Comment by Artbabe** [comment]
thank you for help
ok
please do maneuver on search url
their site uses another template for search
find?...
but you use 
search/title...

what do you think?

sorry my folks are not online

**Comment by Artbabe** [comment]
search for
https://www.imdb.com/search/title/?title=Time+Toys+2016

then use site's search and search for
https://www.imdb.com/find?q=Time+Toys+2016&ref_=nv_sr_sm

**Comment by Artbabe** [comment]
nobody is around me to fix this problem
let me give u this maybe u can solve it


a young coder changed  these :


    const IMDB_SEARCH        = '~text-primary">1[.]</span>\s*<a.href="\/title\/(tt\d{6,})\/(?:.*?)"(?:\s*)>(?:.*?)<\/a>~Ui';
    const IMDB_SEARCH        = '~result_text">\s*<a.href="\/title\/(tt\d{6,})\/(?:.*?)"\s*>(.*)<\/a>~Ui';



            $this->sUrl = 'https://www.imdb.com/search/title/?title=' . rawurlencode(str_replace(' ', '+', $sSearch)) . $sParameters;
            $this->sUrl = 'https://www.imdb.com/find?q=' . rawurlencode(str_replace(' ', '+', $sSearch));




your search url is giving many wrong results
but even with his changes
I got error for

Time Toys 2016
Psychos 2017


and of course for more but maybe 1/3 of that search url

**Comment by bla0r** [comment]
Before the change we used find?q=
Nothing special there. Check the history.

**Comment by Artbabe** [comment]
I tested 50 titles before I ask him to do
search/title is giving very hi error rate
do you see any issue in his code?
please let me tell you
he is capable of debugging his code , its just hes not around
I respect my friends and the only reason I ask you is : TIME

**Comment by bla0r** [comment]
Your coder should do the following things and you'll get the best results:

```
1. create an login to imdb - set original title as default
2. use find?q=
3. save each search result ( title, year, id ) in a vector - maybe as JSON on your local drive.
4. comparing the search words with the result ones
5. fetch that one with the highest agreement
```

**Comment by Artbabe** [comment]
I switched back to your search url
I also changed my platform to use Yours
and now I am working on ur script 
as i said as soon as I finish the task i will give u to add my stuff to urs

you are right
I was wrong about Search url
in total scale , yours is better

but man there are so many mistakes on getURL
I hope this guy can solve it

I asked your email to send u the case but I see you were not interested
do you know me?
I am ARIO owner of scene release
go there in chatroom and call me if u want job

I am leaving this page
have a nice day
I sincerely hope I can get tru this nightmare
users are angry as heck

**Comment by Artbabe** [comment]
please contact my email
ArtBabe
hotmail
I think you worked more than others on this project
I will give u my script
please check why its giving so many mistakes
we will talk about the details which we cant talk here @bla0r

**Comment by bla0r** [comment]
It's NOT a script-side problem.
If you need that, you have to pay a coder to do this. We're doin' this for fun.

Btw. did you checked:
`esc_attr( string $text )`

**Comment by Artbabe** [comment]
can you solve geturl's problem for the titles which have '
?
another necessary item is
checking imdb page , this section:
Also Known as ...

maybe querried title is there and your script can detect getURL

about paying...
unfortunately no-one around me knows imdb like you
you do it please

I hope you read the comment I posted about who I am ,but you can count on my honesty on payment

**Comment by bla0r** [comment]
Before you send the title through the script, you have to add the following line
`esc_attr( $title ) `

This should fix your char problem.

**Comment by Artbabe** [comment]
Dear friend:
if I apply this rule to all vps s , so many unwanted problems will occur because other scripts already consider this rule [no character] 
I wish you could see my servers [about 1000 scripts are communicating in each server to process files]

please can you tell me where I need to add in your imdb script?
I am trying to not be rude and bring the payment each time I talk and I sincerely Apologize for such manners but You have my support on this case ,please solve my problem and I will compensate immediately

where I need to apply such change in imdb.class? [can you do and put the whole changed imdb.class soe where?
my code skills is minimum

problem comes when there is ' or , or such characters which imdb class's response will be empty

They Wont Believe Me 1947
https://www.imdb.com/title/tt0039896/


Broncos House 2015
https://www.imdb.com/title/tt4227776/


Theres Something in the Shadows 2021 
https://www.imdb.com/title/tt14741844/


Nobodys Fool 1994
https://www.imdb.com/title/tt0110684/


and also in case which title has ,  like
September 30 1955
https://www.imdb.com/title/tt0078231/



these are last hour's missing imdb links in posts
I can either send you webmoney/bitcoin
or
I can let you use my site with an ultra premium account [you know my site? dont mention in github it may brings legal issues]
I will ask rapidgator's owner to give you a reward

**Comment by Artbabe** [comment]
@FabianBeiner :
I understood what you said
but The amazing Brains of you ,BL0 and people like you  ,like a young kid from algerian sahara who is like god but life happened to him ! and I cant enjoy his amazing iq/code skills

ALWAYS  there's solution
in fact in my business , there are some public p2p with over 3 mil uniq/day users who already solved this problem for themselves and don't share the code ,like rarbg.to 

we managed to solve all the problems in imdb  , I am sure the character's matter is not big issue
BL0 did remarkable changes BTW he's very capable coder [but I dont compare him to you to avoid those coders who check this post!!]

TVDB's genius slovakian programmer/coder solved this by creating a feature inside the code which gets tvdb's api's result then prioritizes the items based of inputs I gave him
and he finally reached 100% accuracy [this site is the only site which uses tvdb api , others say so many wrong results]
this slovakian genius also static compiled ffmpeg which you see the result [screenshots in my site , 100% can decode the codecs inside media]

my big problem is these people , these super capable people dont know imdb like you 2 amazing people
and I dont have TIME to wait until they learn how imdb works!
users are frustrated of daily mistakes

please check if you can solve ' problem in your script

**Comment by FabianBeiner** [comment]
@Artbabe: As said, there is basically nothing to fix here. The IMDb script is working just fine, it is your side that has problems. And sure, there is always a fix for every user problem - at least programmatically - but this is not our job. If you want that done, you'll have to hire.

Anyway, because you mentioned it: Other sites, that are in your business, also use other techniques to get the URL. For example, each of the posts releases seems to have an information file (something.nfo) that most likely always has the right IMDb URL already written inside. So, I'd suggest thinking more in that direction.

For now, as said, there is nothing to fix at the core function of the script, sorry.

**Comment by Artbabe** [comment]
that function you said is what I use
NFO Processor
that is how I kept the site despite of so many mistakes/day

I said earlier that since 2015 I sent so many site owners to your script , the people who THINK I have responsibility to get the job done!!!!
these people use your script and just for this matter ,they added the note that "Imdb script must be updated" 
one of them is a private tracker with rank 50 global ,i dunno maybe 10 millions users or so

No platform sends characters to imdb in our business [all branches] in fact Scene made it Illegal to use character in title
**the old imdb.class was working perfectly with tiny change** [we were replacing all characters with allowed character which is dash] ,which is not working anymore ,in fact it makes the problem worse

so
**Current imdb.class can not process titles which contain character**

I am asking the people who know "The" Scene Release site , if they found solution , go to chatroom and call my name [Ariel] and I will compensate immediately [consider you're hired]

Dr Ariel Era Jr
The Scene Release

This topic is closed

**Comment by Artbabe** [comment]
wow

**Comment by bla0r** [comment]
The solution is done... i'll test it on more cases, but at this time its very accurate.

**Comment by bla0r** [comment]
`Running: fetchUrl("They Wont Believe Me 1947")
Running cURL: https://www.imdb.com/find?q=They%2BWont%2BBelieve%2BMe%2B1947&s=tt&ttype=ft
YEAR: They Wont Believe Me =>  1947
Accurate: They Wont Believe Me =>  They Won't Believe Me (97.560975609756%) `

`Running: fetchUrl("Theres Something in the Shadows 2021")
Running cURL: https://www.imdb.com/find?q=Theres%2BSomething%2Bin%2Bthe%2BShadows%2B2021&s=tt&ttype=ft
YEAR: Theres Something in the Shadows =>  2021
Accurate: Theres Something in the Shadows =>  There's Something in the Shadows (98.412698412698%) `

`Running: fetchUrl("Nobodys Fool 1994")
Running cURL: https://www.imdb.com/find?q=Nobodys%2BFool%2B1994&s=tt&ttype=ft
YEAR: Nobodys Fool =>  1994
Accurate: Nobodys Fool =>  Nobody's Fool (96%) 
New redirect saved: 3cc36c8a550fc774c7942e209742e33952d92483.redir => https://www.imdb.com/title/tt0110684/reference`

**Comment by Artbabe** [comment]
wow
I am dying to test this script
let me replace my script with yours
I will return back here

**Comment by bla0r** [comment]
I'm still testing it... will commit it soon

**Comment by Artbabe** [comment]
I have tons of failed items
Baby Its Cold Inside 2021
https://i.imgur.com/3EL7Rc6.jpg

**Comment by bla0r** [comment]
Running: fetchUrl("Baby Its Cold Inside 2021")
Running cURL: find?q=Baby%2BIts%2BCold%2BInside%2B2021&s=tt
YEAR: Baby Its Cold Inside =>  2021
Accurate: Baby Its Cold Inside =>  Baby, It's Cold Inside (95.238095238095%)

**Comment by Artbabe** [comment]
Dear Moses , this is remarkable
you made your day useful ;)
I guarantee this one

**Comment by Artbabe** [comment]
ok
just one matter
first , use 
Your search URL

and if t didn't find 
then use find/q...

this is very IMP matter

one of the best thing which I am sure my site will have working imdb , is:
search/title
either gives over 95% accuracy
or
fails

but
find... gives so many wrong result
and never fails LOL [because always gives result, and when there is character in title then almost 100% is wrong]

so 
search/title is amazing
its just it gives empty response for titles with character

have a nice day
calling the day off

**Comment by bla0r** [comment]
I will commit it in couple of hours...

**Comment by Artbabe** [comment]
I want to start working on the idea you brought in
can you tell me the problems which you see in this idea?
I understand this is not your problem , it's mine
if you could share the problems you are getting after applying that change , it can help me to do it faster
time is my enemy but it's Your friend

**Comment by bla0r** [comment]
It will first check ?title... if we get no result it will check find?q= 
this should be the best way... commit now

Running cURL: ?title=Peoples%2BRepublic%2Bof%2BDesire&title_type=feature&release_date=2018-01-01,2018-12-31
Movie not found: Peoples Republic of Desire
Running cURL: find?q=Peoples%2BRepublic%2Bof%2BDesire%2B2018&s=tt&ttype=ft
YEAR: Peoples Republic of Desire =>  2018
Set Result: Peoples Republic of Desire 2018 =>  People's Republic of Desire (98.11320754717%)

**Comment by Artbabe** [comment]
you spent so much time on this project
my users will appreciate your efforts , IQ , Coding skills and dedication 

is it ok I report the issues here if there was issue?
Please contact my email , I need to talk to you about something related to code stuff
Deutschlandik@

googlemail

**Comment by Artbabe** [comment]
indeed good job 
believe it or not it missed only 1 getURL item ,  since my previous comment [6 hours!]

I Do They Dont 2005
https://www.imdb.com/title/tt0449565/

**Comment by Artbabe** [comment]
You are god damn freaking genius (Apology)
@bla0r

**Comment by Artbabe** [comment]
to help ,to turn your script a world class of beauty
I am reporting failed items [if there is!]

Drunkenness 2021
correct is: https://www.imdb.com/title/tt13539152
Note: language is not english [could it be the reason?]

**Comment by bla0r** [comment]
Drunkenness 2021 worked for me.

**Comment by Artbabe** [comment]
ok then
mine got 
https://www.imdb.com/title/tt14391384/
in 3 servers

as I said ,its not big deal at all
Your kid is doing beyond believes

**Comment by Artbabe** [comment]
@BL:
I am working with many coders since 2015
when I see coders' code ,I see how they think
I deeply admire your IQ , and , your skills

**Comment by Artbabe** [comment]
@bla0r :
Kido is busy eating imdb ! 

https://www.imdb.com/title/tt0094846/

https://www.imdb.com/title/tt5004766/  [click on poster then down/left , see the title is even something else]

and many such cases
easy peasy

it missed only 1 item among those which their title was correct (Not entirely correct tho)
[it misses some after people choose wrong title]

which is
UP UP UP 2019

its actually
UP UP and UP 2019
which imdb has
UP UP & UP 2019

Human's brain is just strange thing!

**Comment by bla0r** [comment]
i see the problem.
You can set the sensitivy to use a title, because at this time it only uses a title if its higher than 85 %. You can edit yourself at line: 384
curate: Up Up up =>  Up Up & Up (77.777777777778%)

Gnomeo  works fine:
Running: fetchUrl("Gnomeo and Juliet 2011")
Running cURL: search/title/?title=Gnomeo%2Band%2BJuliet&title_type=feature&release_date=2011-01-01,2011-12-31
Movie not found: Gnomeo and Juliet
Running cURL: find?q=Gnomeo%2Band%2BJuliet%2B2011&s=tt&ttype=ft
YEAR: Gnomeo and Juliet =>  2011
Accurate: Gnomeo and Juliet =>  Gnomeo & Juliet (87.5%) 
New redirect saved: 7308383730fc41d7bd26279d72e9dfb0eaae4fb0.redir => 
tt0377981/reference
Running cURL: /title/tt0377981/reference

**Comment by Artbabe** [comment]
IMDB just said they changed their POSTER location , they say this is the new permanent way , we need to change poster regex

**Comment by bla0r** [comment]
Check: #159

**Comment by Artbabe** [comment]
ok the last matter
is there any feature we can do maneuver  to set
& equal of and
in this script?
the most of problems are coming from &

if not
as I said this script is so accurate

**Comment by bla0r** [comment]
put the following line where you find '//Try Advanced Title Search'

`
$sSearch = preg_replace('/ and /', ' & ', $sSearch);
//Try Advanced Title Search`

**Comment by Artbabe** [comment]
I owe you
I will delete this comment
choose how I can compensate
by using my site or whatever you want
I will always remember you
You have right to ask me a huge favor

**Comment by bla0r** [comment]
it's correct. Let me know if that works better and i'll add it to the class. Cheers.

**Comment by Artbabe** [comment]
ok
here is my final post in this page:
your change worked like miracle
man this was amazing
it just posted correct imdb for whatever it did mistake in matter of &


YOU JUST SOLVED ONE OF THE LAST REMAINED ISSUES IN IMDB SCRIPT

THANK YOU

thank you so very much
how I can contact you?

**Comment by bla0r** [comment]
You're welcome.
You can contact me here. If you have suggestion or problems post a new issue.

**Comment by Artbabe** [comment]
Thank you so truely very very much
I will make sure no-one forgets you in my site
it was honor to meet you
I humbly bow down in front of your Knowledge and your unique SKILLS

Thank you
ALL PROBLEMS SOLVED

**Comment by Artbabe** [comment]
tiny matter remained
about & vs and

will it also work when title has "and"?

I saw it worked for those which have & in title and scene turned them to and
but what about the matter I asked?

**Comment by bla0r** [comment]
`$sSearch = preg_replace('/ and /i', ' & ', $sSearch);`

**Comment by FabianBeiner** [comment]
The discussed issues are not about the script anymore, but about basic usage of PHP. Please use a search engine for this kind of answers.

The topic is locked and closed. You are welcome to open another issue if an error occurs with the script. 

Thanks, @bla0r, for all your work.
