### ISSUE TITLE
bug on getTitle($bForceLocal = false)

### ISSUE THREAD

**Issue by drlearn** [FabianBeiner/PHP-IMDB-Grabber#154]
getTitle($bForceLocal = false) can not get both title and original
only get original title
please fix it

**Comment by FabianBeiner** [comment]
Please provide some debug information.

**Comment by bla0r** [comment]
@drlearn use this function two times.
$original = getTitle($bForceLocal = true);
$title = getTitle($bForceLocal = false);

@FabianBeiner can be closed.
