### ISSUE TITLE
Any trick for conflicts?

### ISSUE THREAD

**Issue by Vitoriel** [FabianBeiner/PHP-IMDB-Grabber#161]
Hi; I sent Beyond Belief 2010 to Imdb grabber and it's output was https://www.imdb.com/title/tt4534390/   - Turned 85 to 95 = same ; turning 85 to 70 = same -  is there any trick we can do to get https://www.imdb.com/title/tt2200832  ?  tests launched in Centos 7 east of european IPs  -Spasibo

**Comment by bla0r** [comment]
I checked the title and I get the right one. If you have issues or problems post a debug.

closed
