### ISSUE TITLE
Problem in IMDB's search is NOT related to this script

### ISSUE THREAD

**Issue by Artbabe** [FabianBeiner/PHP-IMDB-Grabber#162]
Please report problem in imdb's NEW Search Tool , to IMDb
NOT here
Bla0r fixed the problems in fabian's script ,which started after recent change in imdb

if IMDB can NOT detect even simple titles , it's IMDB's problem
and you can see the problem by doing a search in imdb

we started conversation in imdb regarding their search issue

**the script is fine and its doing what it should do**

go to imdb ,search 
Stuff 2015
Walking 2013
[tons of similar titles]
and see what they have done to their search !!

thank to BL for solving imdb grabber's problems

**Comment by bla0r** [comment]
The grabber fetches the right title for the giving titles.

Closed.

**Comment by Artbabe** [comment]
IMDB community answered the ticket
he said
we added a feature in search option which I see it may causes problem for  you guys [he meant me and other site owners who use platforms which dont allow character ]
he said

send your querry in this shape:

Title (4DigitYear)

and dont send 

Title 4DigitYear

he means add (  ) around the 4 digit year
check
Swing 1999
Now send
Swing (1999)

now send
The Grounded 2013
to your script
then send
The Grounded (2013)

to your script

please test their site's search and you see the difference

Now I have a question
do you think it can solve our problem ?
if you think it will work then I will ask someone to help me to add this feature in script

**Comment by bla0r** [comment]
I get the same results if i use it with and without the brackets.

**Comment by Artbabe** [comment]
I know it's not your concern
but you know this script so well
may I ask , what is Your way of doing this?
how I can send the 4 digit year , inside bracket?

so far your solutions worked so well
about characters 
about & vs and/And/AND
and many more

this will give working option for site owners regarding getURL which is the biggest concern of our kinda users

is there any trick/option we can change/add in script to send year of release to imdb in bracket?
I tested 10 of failed items and it solved 9 of them 
or for example
it sends in braket if sensitivity number is not enough to pick the final result

we all know , there is nothing more can be done for the script
this project is indeed closed
the rest is on imdb NOT YOU

**Comment by bla0r** [comment]
Ask your coder what to do. It's really easy.

**Comment by Artbabe** [comment]
I am sorry if I expected too much

**Comment by Vitoriel** [comment]
stupid imdb ruined our sites = error after error in sites use script for fetch imdb id including your site @Artbabe  hehehe ;; you use this script?

**Comment by bla0r** [comment]
I fixed the issue with the year. Will commit it later.

**Comment by bla0r** [comment]
Running: fetchUrl("Swing (1999)")
Running cURL: https://www.imdb.com/search/title/?title=Swing&title_type=feature&release_date=1999-01-01,1999-12-31
New redirect saved: c4517a81bb0c34d73b0600475776c50b70e43bcf.redir => https://www.imdb.com/title/tt0140590/reference
Running cURL: https://www.imdb.com/title/tt0140590/reference
Cache created: 222194320806fd47b84fedf24cf33202b3327971.cache

Running: fetchUrl("Swing (1999)")
Running cURL: https://www.imdb.com/find?q=Swing%2B%281999%29&s=tt&ttype=ft
YEAR: Swing =>  1999
Accurate: Swing =>  Swing (100%) 

Both versions find the right Movie. This is now the best working function. 
I added the following option:
`     /**
     * Set this to true if you want to start with normal search and
     * if you get no result, it will use the advanced method
     * and to false for vice versa
     */
    const IMDB_SEARCH_ORIGINAL = true;`

**Comment by Artbabe** [comment]
RIDICULOUSLY
INSANELY
UNBELIEVABLY 
ACCURATE SCRIPT

WHAT THE HELL YOU HAVE DONE WITH YOUR LAST CHANGE?
GO TO SITE AND SEE YOUR STORM

seriously
go and see what you have done
@bla0r

**Comment by Artbabe** [comment]
I dont understand
I am serious , 
how you did it
imdb's search is bloody mess
this is not an ordinary code

man you are not an ordinary coder
I just hope people see this
You deserve respect

**Comment by Artbabe** [comment]
This is my last comment in imdb grabber

**This is final report:**
after Bla0r's yesterday's Pure-magic
this script has become accurate to the point that I can easily claim:
if Groups posts Correct Title
then
script gets getURL [and as a result poster , plot...]

and
when I see failed item in site
then I delete the release and I post the release with correct title

unbelievably precise
ridiculously accurate

this guy is GOD
