### ISSUE TITLE
PHP8.1 compatibility "sha1(): Passing null to parameter #1 ($string) of type string is deprecated in imdb.class.php on line 300"

### ISSUE THREAD

**Issue by SvenLuebke** [FabianBeiner/PHP-IMDB-Grabber#172]
Hallo!

Due to other dependencies I had to update the system to a newer PHP version (8.1). Using this imdb.class.php will output a warning:

`PHP Deprecated:  sha1(): Passing null to parameter #1 ($string) of type string is deprecated in imdb.class.php on line 300`

Does it occur only on my side? I fixed it by checking for null.

BR,
Sven

**Comment by bla0r** [comment]
Will fix it! Thx!
