### ISSUE TITLE
Grabbing "American Dad!" plot 

### ISSUE THREAD

**Issue by Apollo2000** [FabianBeiner/PHP-IMDB-Grabber#175]
Hello,

When grabbing https://www.imdb.com/title/tt0397306/ getting plot and more:

`"Stan Smith, who works for the C.I.A. and is constantly on the alert for terrorist activity, will go to extremes to protect his beloved America from harm; as evidenced by the terror-alert color code on his fridge, and his frequent knee-jerk reaction of shooting holes in the toaster whenever the toast pops up. In addition to Stan's wife and teenage children, the Smith household has two rather unconventional members. There's Roger, the sarcastic space alien who rescued Stan from Area 51, who deeply resents the fact that he's not allowed to leave the house, and therefore, has been reduced to drinking wine and smoking cigarettes, and Klaus, a lascivious, German-speaking goldfish; the result of a C.I.A. experiment gone seriously wrong, where the C.I.A. tried to give a fish a German man's brain. Stan's son is a dorky teenager who tries to be cool. His wife has had a past life of sex and drugs. Plot Summary | Plot Keywords bare-midriff | 2000s | 2010s | extraterrestrial | stranded-on-earth | See All (70) » | Taglines From the creator of 'Family Guy' comes a man who will stop at nothing to protect his country. Genres Animation | Comedy | Parents Guide View content advisory » Certification Argentina:13 | Australia:M (most episodes, Volume 1-11 DVD) | Australia:MA15+ (some episodes, Volume 12-13 DVD) | Brazil:12 | Bulgaria:C | Canada:14A (Canadian Home Video Rating) | Canada:18A (Manitoba) | Canada:PG (Nova Scotia) | Canada:14A (Ontario) | Canada:G (Quebec) | Canada:14+ (Season 1, 2, 3, 4, 5) | Canada:PG (Season 6, 7, 8) | Chile:TE | Colombia:15 | Finland:K-13 (DVD) | Finland:K-7 (TV) | France:10 | Germany:6 (volume 1) | Germany:16 (volume 7) | Germany:12 (volumes 2-6) | Hong Kong:IIB | India:U | India:PG (some episodes) | Indonesia:17+ (self-applied) | Ireland:PG (one episode) | Ireland:12 (some episodes) | Ireland:15 (some episodes, Volume 1-13 DVD) | Italy:T | Maldives:18+ | Mexico:TV-14 (self-applied) | Netherlands:6 (Season 1) | Netherlands:12 (Season 2) | New Zealand:PG (some episodes) | New Zealand:M (some episodes) | Nigeria:PG | Philippines:SPG | Poland:12 | Russia:16+ | Singapore:M18 | South Africa:13 | South Africa:16 (season 1) | South Korea:19 | Spain:16 (2012 TV rating) | Spain:18 (new TV rating) | Spain:12 (cable rating) | Spain:13 (original TV rating) | Sweden:15 | Turkey:7+ (TV rating) | United Kingdom:12 (some episodes, Volume 1-2 DVD) | United Kingdom:15 (some episodes, Volume 3-13 DVD) | United States:TV-14 | United States:TV-MA | United States:TV-PG (some episodes) | Additional Details Edit Also Known As American Dad (Germany) | Padre Made in USA (Spain) | Американский папаша (Russia) | Американски татко (Bulgaria, Bulgarian title) | Amerikietiškas tėvelis (Lithuania) | | Runtime 22 min | Official Sites Official site | Country United States | Sound Mix Dolby (as Dolby Surround) | Did You Know? Edit Trivia Originally, Klaus was going to be French, and named François. When Dee Bradley Baker auditioned, he told the producers that his French wasn't very good, and that he would read the lines in German instead, they liked his performance so much, they retooled him so he was German. Goofs Early episodes had Roger gradually learn to use disguises to go out into the world; but in later seasons we see that he had actually been using disguises for decades before he met the Smiths. Movie Connections Featured inExcellence in Broadcasting (2010). Soundtracks Good Morning U.S.A. Crazy Credits The Credits end with a Security Guard from Fuzzy Door Productions waving and saying 'Bye, have a beautiful time!' Quotes Roger the Alien: [",`

**Comment by Apollo2000** [comment]
I change line 81 from:
`const IMDB_PLOT          = '~<td[^>]*>\s*Plot\s*Summary\s*</td>\s*<td>\s*<p>\s*(.*)\s*<em~Ui';`
To:
`const IMDB_PLOT          = '~<td[^>]*>\s*Plot\s*Summary\s*</td>\s*<td>\s*<p>\s*(.*)\s*</p>~Ui';`

Problem solved.

**Comment by FabianBeiner** [comment]
Thanks, I've updated the class!
