### ISSUE TITLE
Poster is not working well

### ISSUE THREAD

**Issue by rudnypc** [FabianBeiner/PHP-IMDB-Grabber#176]
Some urls doens't contains "@._", like:
`https://m.media-amazon.com/images/M/MV5BMTMxOGM0NzItM2E0OS00YWYzLWEzNzUtODUzZTBjM2I4MTZkXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UY1200_CR90,0,630,1200_AL_.jpg`

some url contains "@._":
`https://m.media-amazon.com/images/M/MV5BNDkyZGFjZDEtODdiZS00YmJiLWE2NTEtZGIxMTUzN2ZjZjA3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX182_CR0,0,182,268_AL_.jpg`

I'm thinking maybe it's best to remove the "@" from the code.

**Comment by FabianBeiner** [comment]
Please provide some examples of IMDb urls. :)

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by rudnypc** [comment]
https://www.imdb.com/title/tt11976532/

**Comment by rudnypc** [comment]
https://www.imdb.com/title/tt3032476/

**Comment by bla0r** [comment]
@rudnypc fixed #178
