### ISSUE TITLE
a solution found for search issue

### ISSUE THREAD

**Issue by Artbabe** [FabianBeiner/PHP-IMDB-Grabber#180]
hello

please do this way: [add &exact=true ]

https://www.imdb.com/find/?q=spider%202002&s=tt&exact=true&ref_=fn_tt_ex

compare with default search:
https://www.imdb.com/find/?s=tt&q=spider%202002&ref_=nv_sr_sm

and see why we have many mistakes

thanks for your amazing brains [both of you]

I did NOT find this solution
a user found it and asked me to send you in site

**Comment by bla0r** [comment]
You can close this issue, already post it in issues.
