### ISSUE TITLE
getPhotos as image url

### ISSUE THREAD

**Issue by DeseDere** [FabianBeiner/PHP-IMDB-Grabber#189]
How can I properly use this function: public function getPhotos($iLimit = 0, $bMore = true, $sSize = 'small') to get only one photo as url for a background?

I looked thru the examples and I haven't found nothing related to it.

Thanks!

**Comment by FabianBeiner** [comment]
Give `getPhotos(1, false, 'big')` a try. You'll need to link to a local image of yours. Otherwise, take a look at the `getPoster('big', false)` method.
