### ISSUE TITLE
its slow, i only need rating!!

### ISSUE THREAD

**Issue by vasvaridani96** [FabianBeiner/PHP-IMDB-Grabber#190]
Hello!

My problem is that approx. 10 seconds to load all of the data of a movie. I'm trying to interpret the class file, but maybe you have a faster solution: I only need the rating, can we leave out all other information so that it doesn't request it? I see that it also puts them in the cache. Thanks!

**Comment by FabianBeiner** [comment]
No, the script needs to fetch the page to finally parse it. :(

**Comment by vasvaridani96** [comment]
> No, the script needs to fetch the page to finally parse it. :(

Thank you for your quick response, I'm sorry to hear that. :(

I also made an alternative using the HTML DOM parser, which is a bit faster than yours, but if you need a 1-1 value, it might be more efficient for someone. Since imdb's response itself is slow, retrieving a rating with my internet speed takes 3 seconds.

`            include 'dom/simple_html_dom.php'; //https://simplehtmldom.sourceforge.io/docs/1.9/index.html
            $var = $imdbid;
            $html = file_get_html('https://www.imdb.com/title/'.$var);
            $list = $html->find('div[class="sc-bde20123-2 gYgHoj"]',0);
            $list_array = $list->find('span'); 
            for($i = 0;$i<sizeof($list_array);$i++) {
                echo $list_array[$i];
            }`

It returns the value of the rating. If you need another value, you need to understand DOM parser, and replace the find function attributes.

**Comment by FabianBeiner** [comment]
Yeah, if you only need one item, that might be the solution. However, the DOM parsers breaks faster than the regex version, hence my choice back then. ;)
