### ISSUE TITLE
Screens value

### ISSUE THREAD

**Issue by br00m** [FabianBeiner/PHP-IMDB-Grabber#31]
Is it possible to add the screens value out of the box office.

I mean:
Box office/business:

Opening Weekend
$11,364,505 (USA) (21 February 2012) (1,277 Screens)
€1,764,073 (Italy) (5 February 2012) (458 Screens)

Would love to have this added

Grtz br00m

**Comment by FabianBeiner** [comment]
Nope, that value isn't even on the /combined page. So I'm not planing to add this anytime soon. (But go ahead and extend the library if you want!)
