### ISSUE TITLE
Episode List

### ISSUE THREAD

**Issue by HeberPcL** [FabianBeiner/PHP-IMDB-Grabber#59]
Hey,

I can not get the episodes list of a TV-Serie.

Can help?

**Comment by FabianBeiner** [comment]
@HeberPcL, could you please give me more details? Please enable debug (`const IMDB_DEBUG = true;`) and post the output of the script.

Thanks.

**Comment by HeberPcL** [comment]
I saw no method of listing the names of episodes per season.

**Comment by FabianBeiner** [comment]
OK, now I got it. Yes, this is not implemented and most likely never will. Sorry!
