### ISSUE TITLE
Seasons

### ISSUE THREAD

**Issue by vbhook** [FabianBeiner/PHP-IMDB-Grabber#60]
Hi,
if seasons are more than 10 only return '1'
ex: 15 season return 1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 1 / 1 / 1 / 1 / 1 / 1

 and thanks for your great work.

**Comment by FabianBeiner** [comment]
@vbhook, could you provide more information? Please enable debug (const IMDB_DEBUG = true;) and post the output of the script.

Might also be linked to issue #59.

Thanks.

**Comment by FabianBeiner** [comment]
Closed due to inactivity.
