### ISSUE TITLE
Get BoxOffice List

### ISSUE THREAD

**Issue by Global90** [FabianBeiner/PHP-IMDB-Grabber#62]
Please Add Get BoxOffice List in PHP-IMDB-Grabber Class

**Comment by FabianBeiner** [comment]
The `/business` page is difficult to parse. Not only would the script need to do another request (which slows down the output), but the layout of this page seems to be random most of the times. :(

**Comment by Global90** [comment]
for function boxoffice list , only get (Poster,Title,Weekend,Gross,Weeks)

with this link:
http://www.imdb.com/chart/?ref_=hm_cht_sm
