### ISSUE TITLE
Get Full List Image and Video

### ISSUE THREAD

**Issue by Global90** [FabianBeiner/PHP-IMDB-Grabber#64]
Get Full List Image Gallery and Video Gallery.

Image: With Info
Get Poster
Get Poster Wide (Detect With Image Link)
Get Only Poster (All)
Get Image Only
Get Full List Image

{
$arr['poster'] = $this->match('/<div class="photo">.*?<a name="poster".*?><img.*?src="(.*?)".*?<\/div>/ms', $html, 1);
        $arr['poster_large'] = "";
        $arr['poster_full'] = "";
        if ($arr['poster'] != '' && strpos($arr['poster'], "media-imdb.com") > 0) { //Get large and small posters
            $arr['poster'] = preg_replace('/_V1.*?.jpg/ms', "_V1._SY200.jpg", $arr['poster']);
            $arr['poster_large'] = preg_replace('/_V1.*?.jpg/ms', "_V1._SY500.jpg", $arr['poster']);
            $arr['poster_full'] = preg_replace('/_V1.*?.jpg/ms', "_V1._SY0.jpg", $arr['poster']);
        } else {
            $arr['poster'] = "";
        }
}

/**************************************************************/

Video: With Info
Get all Videos
Get all Trailers

    public function getVideos($titleId){
        $html = $this->geturl("http://www.imdb.com/title/${titleId}/videogallery");
        $videos = array();
        foreach ($this->match_all('/<a.*?href="(\/video\/imdb\/.*?)".*?>.*?<\/a>/ms', $html, 1) as $v) {
            $videos[] = "http://www.imdb.com${v}";
        }
        return array_filter($videos);
    }

**Comment by FabianBeiner** [comment]
Could you please open a pull request for this?

**Comment by Global90** [comment]
Get Full List Image Gallery and Video Gallery.

Image: With Info
Get Poster
Get Poster Wide(Backdrop) (Detect With Image Link)
Get Only Poster (All)
Get Image Only
Get Full List Image

regex code in first comment is sample code.

**Comment by Global90** [comment]
Get Full List Image Gallery and Video Gallery.

Image: With Info
Get Poster
Get Poster Wide(Backdrop) (Detect With Image Link)
Get Only Poster (All)
Get Image Only
Get Full List Image

regex code in first comment is sample code.
