### ISSUE TITLE
Genre Sci-Fi gets omitted from getGenre and getGenreAsUrl

### ISSUE THREAD

**Issue by doodley2** [FabianBeiner/PHP-IMDB-Grabber#66]
Genre Sci-Fi gets omitted when pulling genre from imdb movie.

Suggested fix:

    const IMDB_GENRE         = '~<a href="\/Sections\/Genres\/([a-zA-Z_][\w-]*+)\/">(.*)<\/a>~Ui';

**Comment by FabianBeiner** [comment]
Thanks. Will be fixed in v6.0.1.
