### ISSUE TITLE
Poster referral denied

### ISSUE THREAD

**Issue by DeNeDe** [FabianBeiner/PHP-IMDB-Grabber#67]
Any workaround for this?
imdb doesn't support hotlinking.

**Comment by FabianBeiner** [comment]
The download is still working, right? If yes, use this one and serve from your own webserver. :)

**Comment by DeNeDe** [comment]
so if download is activated and i have the image and posted on the server into posters folder it will works by itself?

**Comment by FabianBeiner** [comment]
Check https://github.com/FabianBeiner/PHP-IMDB-Grabber/blob/master/examples/imdb.example.php#L83. This function is downloading the poster by default.

**Comment by DeNeDe** [comment]
i have the same:
<img src="' . $oIMDB->getPoster() . '" width="150" height="150" alt="iMDB Poster" title="iMDB Poster">

**Comment by FabianBeiner** [comment]
Enable debug and post the output of your run, otherwise I can't help.

**Comment by DeNeDe** [comment]
ok, one sec

**Comment by FabianBeiner** [comment]
This sounds more like a problem with the PHP version or something like an APC extension or whatever. I just ran the latest version here and it's working fine.

Maybe check the Apache logs etc.

**Comment by DeNeDe** [comment]
no errors in apache log related to this. :(

**Comment by DeNeDe** [comment]
when ya have time maybe could tinker about that rating i showed ya :100:

**Comment by FabianBeiner** [comment]
Nope, I won't implement this. You can do all if this super easily within your code. :) 

(I'll close this btw. for now as the main issue was, well, not an issue. ;))

**Comment by DeNeDe** [comment]
yeah sure, no problem,  but i just noticed that on PHP 6.5 it wont work, but it works in 5.4
