### ISSUE TITLE
Plot empty when should be 'n/A'

### ISSUE THREAD

**Issue by BrianSpan** [FabianBeiner/PHP-IMDB-Grabber#69]
Sometimes IMDB's combined page will show a heading for Plot but will have no data. See IMDB examples: tt1124379 or tt0187775 .  The getAll() function returns [Plot][value] as an empty string. I believe the function should be returning it as 'n/A' ($sNotFound). It appears the getPlot() function should also check for empty string (or other 'dirty' data even after cleanString() is applied) in addition to matching regex and limit of string. 

(But an excellent program in all respects. Thanks.)

**Comment by FabianBeiner** [comment]
Thanks @BrianSpan for reporting this. And excuse the late reply - I didn't get any notification on this one weirdly. It'll be fixed in 6.0.2 (releasing soon).
