### ISSUE TITLE
year is always n/a

### ISSUE THREAD

**Issue by s1ma0** [FabianBeiner/PHP-IMDB-Grabber#70]
I don't know why but the year is always N/A

**Comment by s1ma0** [comment]
it only happens with some imdb links, like this one http://www.imdb.com/title/tt1231587/?ref_=nv_sr_2

**Comment by BrianSpan** [comment]
http://www.imdb.com/title/tt0083325 also produces year=0 but I think for a different reason.

**Comment by bla0r** [comment]
@s1ma0 and @BrianSpan 
replace the following line in imdb.class.php
const IMDB_YEAR          = '~<a href="\/year\/(?:\d{4})\/">(.*)<\/a>~Ui';

with
const IMDB_YEAR          = '~"og:title".*\(((?:\d{4}))~Ui';

**Comment by FabianBeiner** [comment]
Somehow, I didn't get a notification about this issue. Someone else opened a more generic bug report under #71, so I'm closing this one and will answer on the other thread.
