### ISSUE TITLE
Poster Quality

### ISSUE THREAD

**Issue by dna75** [FabianBeiner/PHP-IMDB-Grabber#73]
Poster image size. 
I updated yesterday to 6.0.2 (i was still running 5.?)

I notice that the small images have gotten smaller. They used to be 182x268pixels. Now they are 94x139px. 

Is there a way to get a bigger poster without setting the class file to Big (they are just to big)?

**Comment by BrianSpan** [comment]
Not sure Fabian can solve this; sometimes it's just weirdness/inconsistency from IMDB. (I'm just a user of the the program myself so I'm not sure.) What movies are you getting very small poster sizes? Is it  several movies or just one?

(For an example of how weird IMDB gets, movie tt0074575 says the title is God's Gun but in the combined page says the title is Diamante Lobo.)

**Comment by dna75** [comment]
It happens with all the movies.
IMDB has a lot of different sizes of the Poster images. It would be nice if we can use another size.
The default Small poster image on the imdb movie page is bigger than the thumb we now get using the small image.

**Comment by FabianBeiner** [comment]
The script is actually not using the poster you’re seeing if you visit IMDb.com, but the one they link in their meta tags. This image is used for sharing on social sites (like `og:image` for Facebook). The reason for this is, that it’s most likely that you can hot link to it without any problems.

Then again, this doesn’t let me (or anyone else) control the size of the picture. There are – if we’re lucky – two sizes: small and big. The exact measurements? Completely different from movie to movie.

So: Sorry, nothing I can do here.

**Comment by dna75** [comment]
Thanks for the reply, The strange thing is that when I use the get poster function of version 5.5.20 the size of the small poster image differs also but is never as small as the small poster image using version 6. I tried using the function of 5.5.2 combined with 6 but don't seem to get that working.

**Comment by FabianBeiner** [comment]
Yeah, the old versions were using another image found in the source than today.
