### ISSUE TITLE
how to change language?

### ISSUE THREAD

**Issue by DevMakoto** [FabianBeiner/PHP-IMDB-Grabber#76]
is possible change language?

example [http://www.imdb.com/title/tt0096283/](url)
use php grabber `getTitle()`
title: My Neighbor Totoro

in website (my language is spanish)
title: Mi vecino Totoro

**Comment by FabianBeiner** [comment]
You can try to change the following:

```
const IMDB_LANG = 'en, en-US;q=0.8';
```
You could try:
```
const IMDB_LANG = 'es, es-ES;q=0.8';
```

If this won't work, you might need an webhost that's located in Spain, because sometimes IMDb prints out the information according to the geo location.
