### ISSUE TITLE
Error when a series has over nine seasons

### ISSUE THREAD

**Issue by exeplay** [FabianBeiner/PHP-IMDB-Grabber#77]
First congratulations on the system. I'm doing some tests with him and noticed a problem. When a series has over nine seasons, he does not return the information correctly ... it is something like this : 1,2,3,4,5,6,7,8,9,1,1,1

For ex. http://www.imdb.com/title/tt0460681/

tks

**Comment by FabianBeiner** [comment]
Fixed in https://github.com/FabianBeiner/PHP-IMDB-Grabber/releases/tag/v6.0.4. :+1:
