### ISSUE TITLE
Search by title, link is true but no title and rate

### ISSUE THREAD

**Issue by Codevz** [FabianBeiner/PHP-IMDB-Grabber#78]
Hi, 

When i try this: 

```PHP
$oIMDB = new IMDB('Scary movie 3');
if ($oIMDB->isReady) {
    echo '<p><a href="' . $oIMDB->getUrl() . '">' . $oIMDB->getTitle() . '</a> got rated ' . $oIMDB->getRating() . '</p>';
} else {
    echo '<p>Movie not found!</p>';
}
```

Output showing me: n/A got rated n/A

But link is true.

**Comment by FabianBeiner** [comment]
I tested exactly your snippet and got the following output:

>[Scary Movie 3](http://www.imdb.com/title/tt0306047/) got rated 5.5

Sorry, there is nothing I can _(have to)_ fix.

**Comment by Codevz** [comment]
Thanks for respond. I'm on localhost, all of other names working fine except "Scary movie, Scary movie 2, Scary movie 3". Not sure why. Anyway thanks ;)

**Comment by FabianBeiner** [comment]
Enable debug and post this output. Without an error I just can't help :(
