### ISSUE TITLE
Ratings is missing from some TV-Series

### ISSUE THREAD

**Issue by weplan9** [FabianBeiner/PHP-IMDB-Grabber#79]
First of all excellent work.

I have encountered a issue where the ratings for the following TV series is = n/A
How ever the on IMDB site the ratings is 9.1

http://www.imdb.com/title/tt0475784/

Thanks again for the beautiful work.

**Comment by bla0r** [comment]
The rating is not available on that page:
http://www.imdb.com/title/tt0475784/combined

In that case we need to parse the main page.

**Comment by FabianBeiner** [comment]
The comment of @bla0r is absolutely correct. No idea why IMDb doesn't show the rating on the Westworld page (anymore?), but for now this is a won't fix. Sorry.
