### ISSUE TITLE
Posters not downloading = 0 bytes

### ISSUE THREAD

**Issue by BrianSpan** [FabianBeiner/PHP-IMDB-Grabber#80]
$IMDB->getPoster('big',true)  does create a file in the posters directory but it is only 0-byte file, The problem may specifically be in function saveImage(). I have tried this with several films. For tests, try tt0040068 , tt2771200

**Comment by BrianSpan** [comment]
EDIT: Apparently, IMDB keeps the posters behind a secure server and they can't be downloaded with CURL unless people either have a security certificate or set any downloads to insecure which is not desirable.

My workaround is this sample code snippet. All that is required should be the location '/posters' under where this IMDBGrabber code is set.

```
$Poster=$IMDB->getPoster('big',false);  //get URL
if ('jpg'==substr($Poster,-3)){  //posters should be JPG but 'no poster' icon is not
    $im = imagecreatefromjpeg($Poster); 
    imagejpeg( $im, $IMDBGrabberPostersDirectory.$IMDB->iId.'.jpg' ); //just need to know where the posters are kept
    }
```

**Comment by FabianBeiner** [comment]
You're right, it has to do with the certification stuff. But in this case we're completely fine to disable this security feature, as nobody is using this script anyway. Right? ;) I'll fix it in the next version, coming soon.

*(Jokes aside, for downloading a poster, we can trust any certificate whatsoever.)*
