### ISSUE TITLE
Original Title

### ISSUE THREAD

**Issue by BrianSpan** [FabianBeiner/PHP-IMDB-Grabber#81]
The script doesn't pick up Original Titles correctly. This appears to be a change in IMDB.

Here are some example pages:
http://www.imdb.com/title/tt0424430
http://www.imdb.com/title/tt0442268

I believe the constant IMDB_TITLE_ORIG should be:
`'~<div class="originalTitle">(.*)<span class="description"> \(original title\)</span></div>~Ui'`

**Comment by FabianBeiner** [comment]
Running it on http://www.imdb.com/title/tt0424430/ with `const IMDB_LANG = 'en, en-US;q=0.8';`, I get the following results:

> Title: **Crying Out Love in the Center of the World**
> (all) Also Known As: Sesangui jungshimeseo sarangeul wichida / South Korea / Оплакивая любовь в самом центре мира / Russia
> Also Known As: **Sekai no chûshin de, ai o sakebu**

So I can't confirm this, everything seems fine.
