### ISSUE TITLE
Stopped grabbing posters about a month ago

### ISSUE THREAD

**Issue by ubkma** [FabianBeiner/PHP-IMDB-Grabber#84]
Instead of show/movie posters it now grabs page content that is unrelated in that field. Would be happy to send debug info - how would I enable it? Very new to solving issues.

**Comment by bla0r** [comment]
You have to set the Debug_Mode in imdb.class.php from false to true.

**Comment by FabianBeiner** [comment]
I gave this a try, but I can't confirm it. And since there was no more information within a month, I'll close it.
