### ISSUE TITLE
Getting - Produced by

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#86]
Hi, in a cache files there is Produced by, but how to get the with ID and name?

**Comment by bla0r** [comment]
Produced by is only working for series...

**Comment by maknol** [comment]
End there isn'a way to work with the movies?

**Comment by bla0r** [comment]
ofc there is a way to implement produced by - i could add it

**Comment by maknol** [comment]
Can you, really? Where can be view that?

**Comment by FabianBeiner** [comment]
I'll check if I can add it while fixing https://github.com/FabianBeiner/PHP-IMDB-Grabber/issues/87.
