### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#88]
Hi, i downoaded the last version, and get that issues - http://www.imdb.com/title/tt6911608/reference ,
i'm browse it from Italy and it's get me Itaian title, but i want original title. How to get the original one? 
From **paulitap** script, i'm get the original one.

**Comment by xsabianus** [comment]
http://www.imdb.com/title/tt5680152/ title code, gives an error.

**Comment by weplan9** [comment]
I am also facing this issue.

My servers are in Europe and somehow it picking up French Title.

I think it should be default to English.

**Comment by FabianBeiner** [comment]
I think IMDb does not care anymore about the sent `Accept-Language` header, but instead gives you localized content by location.

**Comment by FabianBeiner** [comment]
Can you guys try these regex?

```php
    const IMDB_TITLE         = '~property=\'og:title\' content="(.*)"~Ui';
    const IMDB_TITLE_ORIG    = '~</h3>(?:\s+)(.*)(?:\s+)<span class=\"titlereference-original-title-label~Ui';
```

**Comment by FabianBeiner** [comment]
Fixed in https://github.com/FabianBeiner/PHP-IMDB-Grabber/tree/v6.0.7.

**Comment by weplan9** [comment]
Thanks for fixing this.

Make sure to clear the Cache folder and use the following to get the title:

`$oIMDB->getTitle(true);`
