### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by silvah2** [FabianBeiner/PHP-IMDB-Grabber#91]
example:

running: fetchUrl("http://www.imdb.com/title/tt0033467/")

Running cURL: http://www.imdb.com/title/tt0033467/reference

Cache created: 1e02040df4fd6f9e4df440f41d3c30a2130abd4b.cache

http://www.imdb.com/title/tt0033467/

(all) Also Known As: n/A

Also Known As: n/A

Aspect Ratio: n/A

Awards: n/A

Cast: n/A

Cast: n/A

Cast and Character: n/A

Cast and Character: n/A

Certification: n/A

Color: n/A

Company: n/A

Company: n/A

Country: n/A

Country: n/A

Creator: n/A

Creator: n/A

Director: n/A

Director: n/A

Genre: n/A

Genre: n/A

Is released: No

Language: n/A

Language: n/A

Location: n/A

Location: n/A

MPAA: n/A

Plot: n/A

Plot Keywords: n/A

Poster: n/A

Rating: n/A

Release Date: n/A

Runtime: n/A

Seasons: n/A

Seasons: n/A

Sound Mix: n/A

Tagline: n/A

Title: n/A

Trailer: n/A

Url: http://www.imdb.com/title/tt0033467/

User Review: n/A

Votes: n/A

Writer: n/A

Writer: n/A

Year: n/A

**Comment by FabianBeiner** [comment]
It is, just get the latest version.

**Comment by silvah2** [comment]
I have your latest version, 6.0.7

**Comment by FabianBeiner** [comment]
Yeah, and this one is working 🤷‍♂:

> Citizen Kane
> 
> (all) Also Known As: El ciudadano / Argentina / Citizen Kane / Austria / Cidadão Kane / Brazil / Ciudadano Kane / Chile / Občan Kane / Czech Republic / Citizen Kane / Germany / Citizen Kane / Denmark / Den store mand / Denmark / Ciudadano Kane / Spain / Citizen Kane / Finland / Citizen Kane / France / Ο πολίτης Κέιν / Greece / Građanin Kane / Croatia / Aranypolgár / Hungary / Quarto potere / Italy / Shimin Kein / Japan / El ciudadano Kane / Mexico / Obywatel Kane / Poland / O Mundo a Seus Pés / Portugal / Cetateanul Kane / Romania / Građanin Kejn / Serbia / Гражданин Кейн / Russia / En sensation / Sweden / Drzavljan Kane / Slovenia / Громадянин Кейн / Ukraine / El ciudadano / Uruguay / El ciudadano / Venezuela
> 
> Also Known As: John Citizen, U.S.A. (United States) | American (United States) | Ciutadà Kane (Spain, Catalan title) | Ciudadano Kane (Spain) | O politis Kane (Greece)
> 
> Aspect Ratio: 1.37 : 1
> 
> Awards: Won 1 Oscar. Another 9 wins & 13 nominations.

etc.
