### ISSUE TITLE
Year MPAA Director(Creator) StoryLine Not working on Series

### ISSUE THREAD

**Issue by ronovar** [FabianBeiner/PHP-IMDB-Grabber#92]
When you try series to get data i get all n/A for:

Year
MPAA
Director(Creator)
StoryLine

if is possible to fix this in new version of this script?

**Comment by FabianBeiner** [comment]
https://github.com/FabianBeiner/PHP-IMDB-Grabber#bugs

**Comment by bla0r** [comment]
YEAR, MPAA has been fixed and committed. I can't reproduce director and storyline, cause it works for me.

**Comment by ronovar** [comment]
Thanks...Year and MPAA works now (using your fix) but Director does not work for me for series (for movies it works) can you please share your regex for director? This is director regex from php script:

const IMDB_DIRECTOR      = '~<div[^>]*>\s*(?:Director|Directors)\s*:\s*<ul[^>]*>(.+)</ul>~Uxsi';

Also small tutorial how we can add own regex will be great...i im using PHP alot..but i don't know where it gets the files for regex to be read...from cache directory?

**Comment by bla0r** [comment]
For series you have to use getCreator() instead of getDirector().

Will take a look for budget.

**Comment by bla0r** [comment]
@ronovar budget has been added as getBudget()

**Comment by ronovar** [comment]
Thanks...now is working all perfect.
