### ISSUE TITLE
Using with Codeigniter

### ISSUE THREAD

**Issue by Damodarix** [FabianBeiner/PHP-IMDB-Grabber#94]
Hello guys, as today many people uses Codeigniter framework it would be nice if you could create little tutorial on how to make it work with Codeigniter or create example with library, controller and view.

Thanks in advance.

**Comment by ibrahimnasser07** [comment]
I'd like to unsubscribe please

**Comment by FabianBeiner** [comment]
@Damodarix: Since nobody answered, and I'm not a Codeigniter users myself, I'm closing this issue for now. But I hope you got it working meanwhile.
