### ISSUE TITLE
Posters new URL

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#95]
Hi, again imdb changes their code, this time - url poster.

I changed 
`const IMDB_POSTER        = '~<link rel="image_src" href="(.*)">~Ui';`

with
`const IMDB_POSTER        = '~<meta\s*property=\'og:image\'\s*content="(.*)">~Ui';`

and now is O.K.

**Comment by FabianBeiner** [comment]
Just FYI: I can't confirm this. Posters are still working with the old regex.

**Comment by Honkman32** [comment]
No, unfortunately not.
It loads nothing or only 0B files (poster).

**Comment by FabianBeiner** [comment]
As said, it works with the latest version here. Nothing I can fix.

**Comment by maknol** [comment]
For some movies, it'd really "loads nothing or only 0B files (poster)".

**Comment by FabianBeiner** [comment]
That doesn't apply here, because I'm not using any fixed hostnames.

So, unless someone is going to post a proper bug report (https://github.com/FabianBeiner/PHP-IMDB-Grabber#bugs), there is nothing to fix.

**Comment by Honkman32** [comment]
![unbenannt](https://user-images.githubusercontent.com/7806332/37735493-8b24b760-2d4e-11e8-8f58-7512427e29f7.jpg)
Ich hoffe das reicht als Fehlermeldung.

**Comment by FabianBeiner** [comment]
403 ain't a script error (https://www.wikiwand.com/en/HTTP_403).
