### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#96]
Hi, just now I see that script stoped to work, i getting this massage:

> HTTP/1.1 302 FoundDate: Tue, 17 Apr 2018 08:25:04 GMTServer: ServerLocation: https://www.imdb.com/title/tt6791096/referenceContent-Length: 230Content-Type: text/html; charset=iso-8859-1<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>302 Found</title></head><body><h1>Found</h1><p>The document has moved <a href="https://www.imdb.com/title/tt6791096/reference">here</a>.</p></body></html>

**Comment by vsystech** [comment]
Hello, i have a some problem!

**Comment by maknol** [comment]
The URL from now is HTTPS
