### ISSUE TITLE
new versions still dont work for me

### ISSUE THREAD

**Issue by silvah2** [FabianBeiner/PHP-IMDB-Grabber#98]
Running: fetchUrl("https://www.imdb.com/title/tt0033467/")

Running cURL: https://www.imdb.com/title/tt0033467/reference

array(27) { ["url"]=> string(46) "https://www.imdb.com/title/tt0033467/reference" ["content_type"]=> string(23) "text/html;charset=UTF-8" ["http_code"]=> int(200) ["header_size"]=> int(1202) ["request_size"]=> int(396) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(2.538632) ["namelookup_time"]=> float(8.9E-5) ["connect_time"]=> float(0.141749) ["pretransfer_time"]=> float(0.467843) ["size_upload"]=> float(0) ["size_download"]=> float(0) ["speed_download"]=> float(0) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(-1) ["starttransfer_time"]=> float(2.538503) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(13) "52.94.228.167" ["certinfo"]=> array(0) { } ["primary_port"]=> int(443) ["local_ip"]=> string(11) "xxx" ["local_port"]=> int(52478) ["contents"]=> bool(false) }

cURL error: 

Movie not found: https://www.imdb.com/title/tt0033467/

Running: fetchUrl("https://www.imdb.com/title/tt5680152/reference")

Running cURL: https://www.imdb.com/title/tt5680152/reference

array(27) { ["url"]=> string(46) "https://www.imdb.com/title/tt5680152/reference" ["content_type"]=> string(23) "text/html;charset=UTF-8" ["http_code"]=> int(200) ["header_size"]=> int(1202) ["request_size"]=> int(396) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(1.318213) ["namelookup_time"]=> float(7.7E-5) ["connect_time"]=> float(0.147316) ["pretransfer_time"]=> float(0.477761) ["size_upload"]=> float(0) ["size_download"]=> float(0) ["speed_download"]=> float(0) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(-1) ["starttransfer_time"]=> float(1.318104) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(13) "52.94.228.167" ["certinfo"]=> array(0) { } ["primary_port"]=> int(443) ["local_ip"]=> string(11) "xxx" ["local_port"]=> int(52480) ["contents"]=> bool(false) }

cURL error: 

Movie not found: https://www.imdb.com/title/tt5680152/reference

php7.2.4 with lighttpd
Any advices?

thanx

**Comment by silvah2** [comment]
CURLOPT_ENCODING       => '',

works after changing this to empty, thanx

**Comment by FabianBeiner** [comment]
Ahh, so a local issue. Your server probably doesn't support gzip.
