### ISSUE TITLE
All results returning n/A

### ISSUE THREAD

**Issue by myopenflixr** [FabianBeiner/PHP-IMDB-Grabber#99]
Hello,

I use your script on my media server and have updated imdb_class.php to the most recent version from github.

Now I am getting all results returned as "n/A".

I installed your imdb.test.php on my server just to check if I had errors on my config and here is an abbreviated example on what my browser displays with your test script.

----------------------------------------
https://www.imdb.com/title/tt0033467/

(all) Also Known As: n/A

Also Known As: n/A

Aspect Ratio: n/A

Awards: n/A

Cast: n/A

Cast: n/A

Cast and Character: n/A

Cast and Character: n/A

Certification: n/A

Color: n/A

Company: n/A

Company: n/A

Country: n/A

Country: n/A

Creator: n/A

Creator: n/A

Director: n/A

Director: n/A

Genre: n/A

Genre: n/A

Is released: No

Language: n/A

Language: n/A

Location: n/A

Location: n/A

MPAA: n/A

Plot: n/A

Plot Keywords: n/A

Poster: n/A

Rating: n/A

Release Date: n/A

Runtime: n/A

Seasons: n/A

Seasons: n/A

Sound Mix: n/A

Tagline: n/A

Title: n/A

Trailer: n/A

Url: http://www.imdb.com/title/tt0033467/

User Review: n/A

Votes: n/A

Writer: n/A

Writer: n/A

Year: n/A
----------------------------------------------

Any suggestions on how I can resolve this issue?

Thanks,
Mike

**Comment by myopenflixr** [comment]
I figured out the issue. Your imdb_class.php still references http for imdb.

I manually changed all the http references to https and working fine.

**Comment by FabianBeiner** [comment]
Nope, you didn't use the latest version then. Because HTTPS is what got explicitly fixed there. ;) But glad it works for you again.
